# Generated by Django 5.0.2 on 2024-03-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_aktor_extrainfo_ocena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='rezyser',
        ),
        migrations.AddField(
            model_name='aktor',
            name='filmy',
            field=models.ManyToManyField(to='filmy.film'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='film',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmy.film'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='punkty_widzow',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocena',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmy.film'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (4, 'Dramat')], null=True),
        ),
    ]
