# Generated by Django 5.0.2 on 2024-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0003_remove_extrainfo_rezyser_aktor_filmy_extrainfo_film_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModelLab4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=64, unique=True)),
                ('rok', models.PositiveSmallIntegerField()),
                ('opis', models.TextField(default='')),
                ('premiera', models.DateField(blank=True, null=True)),
                ('imdb_pkts', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Komedia'), (0, 'Inne'), (1, 'Horror'), (4, 'Dramat'), (3, 'Sci-fi')], null=True),
        ),
    ]
