# Generated by Django 5.0.2 on 2024-03-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_filmmodellab4_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Komedia'), (3, 'Sci-fi'), (1, 'Horror'), (4, 'Dramat'), (0, 'Inne')], null=True),
        ),
    ]
