# Generated by Django 5.0.2 on 2024-03-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0005_alter_extrainfo_gatunek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='film',
            new_name='filmy',
        ),
        migrations.RemoveField(
            model_name='extrainfo',
            name='punkty_widzow',
        ),
        migrations.AddField(
            model_name='aktor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktorzy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='rezyser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Dramat'), (2, 'Komedia'), (3, 'Sci-fi'), (0, 'Inne'), (1, 'Horror')], null=True),
        ),
    ]
